# Generated by Django 4.1.7 on 2023-04-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("surname", models.CharField(max_length=60)),
                ("feedback", models.TextField()),
                ("rating", models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(name="Feedbacc",),
    ]
