# Generated by Django 4.1.7 on 2023-04-26 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_feedback_delete_feedbacc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                max_length=10, validators=[django.core.validators.MinLengthValidator(2)]
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="surname",
            field=models.CharField(
                max_length=60, validators=[django.core.validators.MinLengthValidator(3)]
            ),
        ),
    ]
