# Generated by Django 4.1.7 on 2023-04-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0002_movie_budget_movie_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie", name="slag", field=models.SlugField(default=""),
        ),
    ]
