# Generated by Django 4.1.7 on 2023-04-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0003_movie_slag"),
    ]

    operations = [
        migrations.RenameField(model_name="movie", old_name="slag", new_name="slug",),
    ]
