# Generated by Django 4.1.7 on 2023-04-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0004_rename_slag_movie_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
