# Generated by Django 4.1.7 on 2023-04-22 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0007_alter_movie_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.CharField(default="Тарантино", max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="budget",
            field=models.IntegerField(
                default=1000000,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
