# Generated by Django 4.1.7 on 2023-04-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0009_movie_director_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.CharField(max_length=100)),
                ("l_name", models.CharField(max_length=100)),
                ("director_email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(model_name="movie", name="director",),
        migrations.RemoveField(model_name="movie", name="director_email",),
    ]
