# Generated by Django 4.1.7 on 2023-04-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0014_alter_movie_director"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.CharField(max_length=100)),
                ("l_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Мужчина"), ("F", "Женщина")],
                        default="M",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(to="movie_app.actor"),
        ),
    ]
