# Generated by Django 4.1.7 on 2023-04-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0017_dressingroom_actor_dressing"),
    ]

    operations = [
        migrations.RemoveField(model_name="actor", name="dressing",),
        migrations.DeleteModel(name="DressingRoom",),
    ]
