# Generated by Django 4.1.7 on 2023-04-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0018_remove_actor_dressing_delete_dressingroom"),
    ]

    operations = [
        migrations.CreateModel(
            name="DressingRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor", models.IntegerField()),
                ("number", models.IntegerField()),
            ],
        ),
    ]
