# Generated by Django 4.1.7 on 2023-04-24 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0019_dressingroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="dressing",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="movie_app.dressingroom",
            ),
        ),
    ]
